### ISSUE TITLE
Nextcloud explorer is empty (special characters in username, e.x. @)

### ISSUE THREAD

**Issue by robert-wettstaedt** [vauvenal5/yaga#41] opened 2021-01-01 14:21 UTC
## Expected Behavior
In the files explorer of my Nextcloud server, I expect to see the files and directories that are saved there.

## Actual Behavior
In the files explorer of my Nextcloud server, no files and directories are being displayed.

## Steps to Reproduce the Problem
Following the [Quickstart steps](https://vauvenal5.github.io/yaga/quickstart/) of the docs
  1. Fresh installation
  2. Login to Nextcloud
  3. Open the Home-View settings 
  4. Select the Path setting 
  5. Change the destination from your local phone to your Nextcloud server 
  6. A loading indicator is being shown
  7. The loading indicator fades away
  8. The explorer is empty

## Screenshots
- What the file explorer looks like in Yaga:
![Screenshot_20210101-145844_Yaga](https://user-images.githubusercontent.com/3035576/103440188-7682d800-4c3b-11eb-9e94-da128ce8aa40.png)

- Proof that there are files and directories in the root of my Nextcloud server based on the Nextcloud app:
![Screenshot_20210101-145850_Nextcloud](https://user-images.githubusercontent.com/3035576/103440189-78e53200-4c3b-11eb-91d6-a9af44e72169.png)

## Specifications

- Yaga version: 0.15.10
- Android version: 11
- Nextcloud version: 19.0.3

**Comment by vauvenal5** [comment] 2021-01-03 13:55
Hmm thats odd. It seems like when trying to fetch the file list from your cloud something goes wrong. Might have something to do with the Nextcloud version. I will have to try it out. Can you try reseting the app and performing the login again. Also does your `browse view` stay empty too?

**Comment by sc21221** [comment] 2021-01-04 17:37
have the same behaviour.
also after un-/reinstalling and fresh login.
browse view is empty also.

- Yaga: 0.15.10
- Android: 11
- Nextcloud 20.0.3.2

**Comment by politas** [comment] 2021-01-05 11:47
I also have the same behaviour.
NextCloud Yaga 0.15.10
NextCloud 20
Android 10

**Comment by vauvenal5** [comment] 2021-01-05 16:11
Can anyone provide logcat files for this behavior? I am having troubles reproducing the issue and thus narrowing it down.

**Comment by theuser18** [comment] 2021-01-05 16:39
> 
> 
> Can anyone provide logcat files for this behavior? I am having troubles reproducing the issue and thus narrowing it down.

I am new to all of this, so if you could tell me how to properly use logcat while I reproduce the problem I would be happy to.

**Comment by politas** [comment] 2021-01-06 21:09
I hope this is what you need. https://www.dropbox.com/s/j3106bosphqn8jc/logcat.txt?dl=0

**Comment by vauvenal5** [comment] 2021-01-07 11:05
Thx, I will have a look.

What devices are you running on?

**Comment by robert-wettstaedt** [comment] 2021-01-07 14:19
Pixel 5 for me

**Comment by minosimo** [comment] 2021-01-07 15:18
Same issue here, Andriod 10 Havoc OS, Nextcloud 20.0.2.2. Here's a logcat from clicking "Grant access" then Browse view.
[browse_view.txt](https://github.com/vauvenal5/yaga/files/5782379/browse_view.txt)

**Comment by vauvenal5** [comment] 2021-01-07 16:53
I just published version v0.16.2 which improves logging and the error behavior of the foreground worker. Would appreciate it if you could send me again some logcat files once you have the new version.

Based on what I could see so far from @politas logs I believe that the worker thread is crashing for some unknown reason, the new logging should be able to capture the reason.

@SimonCDalzell regarding your log... there are two strange things in there. First of all some error regarding the init process which I will have to look into and 2nd there is a `NotAuthenticated` response from your server. Did you try clearing the app data and authenticating a 2nd time?

**Comment by SimonCDalzell** [comment] 2021-01-07 17:10
Thanks. Since the new log includes some mildly sensitive info, is there an alternate contact I could send them to?

**Comment by minosimo** [comment] 2021-01-07 17:19
Yes, I tried a few times starting from scratch, always with the same result. I did notice that I would get "multiple invalid logins, login throttled to 30s" messages when I wasn't expecting them since I always paste in the login info. I have no idea if that's related, could just be user error.

I logged the first launch, log in and browse on 0.16.2, which I sent to your gmail since it includes vaguely sensitive info.

**Comment by politas** [comment] 2021-01-07 19:25
I'm still only seeing 0.15.10 on F-droid

**Comment by vauvenal5** [comment] 2021-01-07 21:02
@SimonCDalzell thank you for your logs. I think I found the issue. I guess everyone having this issue has an email address as username, right?

**Comment by robert-wettstaedt** [comment] 2021-01-08 07:53
Yes I do

**Comment by fcrozat** [comment] 2021-01-08 08:14
In my case, no, my login is not an email address.

**Comment by aginies** [comment] 2021-01-08 08:59
I have the same error here, my listing is empty. I didn't enalbe the preview on the nextcloud server, but sounds like the app try to display preview image:

nc/index.php/core/preview.png?file=%2Fnc%2FNextcloud.png&x=128&y=128&a=true&mode=cover&forceIcon=false

Is there is any error trying to detect if there is a preview available or not?

**Comment by vauvenal5** [comment] 2021-01-08 10:14
Hi everyone,

I just published v0.16.3. This should fix the issue for everybody who is using usernames with special characters. I am not sure how long the F-Droid release cycle needs to build and publish new apps. However, I saw that the update mechanism did pick up the new versions from yesterday and updated the meta-file correctly: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.github.vauvenal5.yaga.yml

@fcrozat can you send me your logcat logs? Ideally from at least v0.16.2 so we have the improved logging output. I believe that something else is the issue in your case.

@aginies if the preview generator plugin is not active then previews are generated by Nextcloud on the fly, so this should not be an issue. Does your browse view also stay empty? Does your username contain any special characters? Are you able to provide logcat logs?

**Comment by sc21221** [comment] 2021-01-08 12:38
login is now possible! seems to work (had also email as username).
got v0.16.3 from playstore.
thx for quick fixing :-)

**Comment by fcrozat** [comment] 2021-01-08 13:10
both me and @aginies are using the same instance:

from the logs, I noticed (I replace the server real hostname to www.foobar.com in the logs,  nextcloud is installed in https://www.foobar.com/nc/ ):

[01-08 13:56:06.147 12347:13828 I/flutter]
[38;5;208m[W] NextcloudFileManager - Emiting list! (nc://fcrozat@www.foobar.com/nc/)[0m

[01-08 13:56:06.147 12347:13082 I/flutter]
[38;5;208m[W] FileListLocalManager - deb12f60-51b0-11eb-b74e-21838d65f07b (done - manager key)[0m

[01-08 13:56:06.148 12347:13082 I/flutter]
[38;5;208m[W] FileListLocalManager - deb12f60-51b0-11eb-b74e-21838d65f07b (done - event key)[0m

[01-08 13:56:06.148 12347:13828 I/flutter]
404

[01-08 13:56:06.148 12347:13828 I/flutter]
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name //nc could not be located</s:message>
</d:error>

**Comment by vauvenal5** [comment] 2021-01-08 13:54
@fcrozat / @aginies I moved you to a new issue: #52 

For anyone reading this thread beyond this post if your issue is not based on special characters in the username please open a new issue with your problem description.

**Comment by vauvenal5** [comment] 2021-01-12 16:30
Closing this as fixed, fell free to reopen if necessary.

**Closed as completed by vauvenal5** 2021-01-12 16:30 UTC
Labels: bug
