### ISSUE TITLE
Can't "open in browser" to log in

### ISSUE THREAD

**Issue by ruben-tura** [vauvenal5/yaga#101] opened 2021-03-13 16:32 UTC
Hi,
I'm kinda new to this, so I'll try and explain myself.

I have a nextcloudPi set up at home, and I'm trying to connect to it. When I normally (outside of Yaga) connect to it via browser, it always says "secure connection failed", and I have to click on " advance anyway" to proceed.

Now, when I try and connect with Yaga, the thing is, if I click "continue", it just gives me a blank screen, and if I click "open in browser" it just opens a popup, where I should click "trust", but if I do, it just opens the same popup again.

How can I proceed?

**Comment by vauvenal5** [comment] 2021-03-20 11:49
https://github.com/vauvenal5/yaga/issues/34#issuecomment-803296643

**Comment by vauvenal5** [comment] 2021-03-20 11:58
Duplicate of #34

**Closed as completed by vauvenal5** 2021-03-20 11:58 UTC
Labels: duplicate, investigate
