### ISSUE TITLE
Root Mapping is not preserved

### ISSUE THREAD

**Issue by vanitasvitae** [vauvenal5/yaga#38] opened 2020-12-30 17:23 UTC
Hey,
thanks for this app :)

I have the issue that the root mapping appears to reset across restarts of the app.

To reproduce:
* Set path to nc://user@cloud.tld/Images/MyFolder
* in global settings change root mapping to
  * remote: nc://user@cloud.tld/Images/MyFolder
  * local: file://device.local/DCIM/Camera
* restart the app

While these settings work immediatelly after I set them (synced files have a green checkmark, remote files have a cloud symbol), as soon as I restart the app, it appears to forget the root mapping.

Happy Hacking!

**Comment by vauvenal5** [comment] 2020-12-30 22:26
Hi,

thanks for the report! So if I understand it correctly you are mapping a sub path on your cloud to a path on your device, right?
cloud: `/` <-- root
cloud: `/Images/MyFolder` <-- actually mapped path, which is a subpath of root

**Comment by vanitasvitae** [comment] 2020-12-30 22:28
yeah that's correct :)

**Comment by vauvenal5** [comment] 2021-01-05 16:05
should be fixed in v0.15.11

**Comment by Thovi98** [comment] 2021-01-16 22:06
I have same issue, but I map the root of my Nextcloud to a path on my device (the one set by the Nextcloud App by default). I'm using latest 0.18.2 version of Yaga. Don't know how I can help investigate ?

**Comment by vauvenal5** [comment] 2021-01-17 08:56
Hi @Thovi98 

your mapping is pointing from your Nextcloud root to your app data folder, if I understood correctly? How exactly is the mapping lost? What are the effects you are experiencing?

**Comment by Thovi98** [comment] 2021-01-17 09:04
Yes it's that. Sometimes (randomly), when I go to the app, I don't see my downloaded pictures. When I go to the mapping settings, I see that the original local path file://device.local/Android/data/com.github.vauvenal5.yaga/files/user@mynextcloud is used, instead of the modified one. 

I just discoverd one thing I think you could reproduce : 
- open the app
- change the local path (I've changed it to file://device.local/Android/media/com.nextcloud.client/nextcloud/user@mynextcloud)
- Click on select to save
- Quit the app
- Open the app to the mapping settings
- See it still the modified path
- --> instead of just leaving, click on select
- Go again in mapping settings and see that it's the original path.

Thanks for your help

**Comment by vauvenal5** [comment] 2021-01-20 08:22
Thanks, I was able to reproduce this. Fix will be up shortly.

**Comment by vauvenal5** [comment] 2021-01-23 13:51
fixed in `v0.19.1`

**Comment by vauvenal5** [comment] 2021-01-25 16:42
@Thovi98 can you confirm the issue is fixed for you, or simply close the ticket once it is confirmed :)

**Comment by Thovi98** [comment] 2021-01-27 21:01
Yes, sorry for the late reply, I just tested it and it works great ! Your app goes greater and greater 🎉 
I cannot close this issue because I’ve not opened it, but it’s resolved, thanks !

**Closed as completed** 2021-01-28 08:17 UTC
Labels: bug, v1.0.0
