### ISSUE TITLE
Can't login to my nextcloud server, blank white screen

### ISSUE THREAD

**Issue by ioogithub** [vauvenal5/yaga#106] opened 2021-03-19 00:11 UTC
1. Open the app
2. Click on 3 bars and select Login
3. Enter nextcloud address and click Continue.

The result is a white screen with Sign in...

The only action here is to click the back button.

If I try to use the Open in browser button, I get a message:

Untrusted Certificate
Do you trust this certificate?

Click "Trust" 

nothing happens, the screen just refreshes. Click trust again and the screen again refreshes.

There is nothing else to try here.

I can't see any other path to sign in. I am signed in using the nextcloud android app and in a browser without errors, not sure why I can't use this app.

**Comment by vauvenal5** [comment] 2021-03-19 10:44
- Which yaga version are you using?
- Are you using a PiHole?
- Are you using a custom CA?
- Can you send me your logcat logs via email?

**Comment by ioogithub** [comment] 2021-03-19 16:43
I am using yaga version 0.22.3 downloaded from f-droid
I am not using a piHole,
I am using a self-signed certificate, the one provided with Apache on Ubuntu. I don't know if this means custom.

When I click Open in Browser, it displays the message: Do you trust this certificate and it displays the correct Subject, Issuer and Fingerprint so it is able to detect and parse cert data correctly. When I press the Trust button however it does nothing but refresh the window.

The continue button on the other hand is just a blank white screen with the title "Sign in..." no error message or other feedback.

What is the format for entering the URL address? are you looking for:

- username@server/installation
- server/installation

I also found that if i enter some random string (test.net) I get the same blank white page.

Since writing this ticket, I have installed several other Nextcloud android apps on the same phone, they are all working:

- Notes
- Deck
- Talk
- News

These seem to get the credentials from the Nextcloud files app.

The 'Cookbook' asked for manual credentials and this worked as well.

While these other apps are nice, an online photo gallery is the top reason why I installed Nextcloud so I would really like to get this working.

**Comment by vauvenal5** [comment] 2021-03-19 18:57
- support for Self-Signed Certs was added very latte, since it was not a priority for me, and there seems to be a bug in it, see also #101 and #34 (there I am waiting for a new log-file from @Pato05 which will hopefully help in finding the issue)
- Yaga is build with Flutter and therefore unable to use to login over the Files app  flow like offered by Deck for example
- url is expected to be of the format `host:port/path`
- only the `Open in Browser` flow support self signed certs, so the `continue` button will not help you
- to get to the bottom of this issue I will need a new set of logs from `v0.22.4` or higher, FDroid is usually a few days behind with publishing new versions
- easiest way to fix it is if you set up your Nextcloud with a trusted cert, [Let's encrypt](https://letsencrypt.org/) is a good place to get one, if this is not an option for you, you will have to wait for a bugfix

**Comment by Pato05** [comment] 2021-03-19 19:57
@vauvenal5 I'm so sorry, I forgot about this, will try to send the logcat within an hour. By the way, if this may help, you may use Java within the app by using the `MethodChannel` class and by implementing the functions inside your java file

**Comment by vauvenal5** [comment] 2021-03-20 11:48
https://github.com/vauvenal5/yaga/issues/34#issuecomment-803296643

**Comment by vauvenal5** [comment] 2021-03-20 11:57
@Pato05 about the `MethodChannel`, I am aware of that option, however, implementing the entire communication flow as a Java class only to support self-signed certificates is somewhat extensive. Also it kind of defies the purpose of using a platform independent framework for building the app.

**Comment by vauvenal5** [comment] 2021-03-20 11:57
Duplicate of #34

**Closed as completed by vauvenal5** 2021-03-20 11:57 UTC
Labels: duplicate, investigate
