### ISSUE TITLE
External storage

### ISSUE THREAD

**Issue by IamSAB** [vauvenal5/yaga#114] opened 2021-03-26 06:10 UTC
Hi, thank you for the app, I really like the app and the idea.

I got my nextcloud files on my external sd card. Currently I cannot map my local path to my sd card folder, as I it is only possible to select folders from my local storage.

**Comment by vauvenal5** [comment] 2021-03-27 15:41
Duplicate of #23. 

PS: i will consider moving this forward in the timeline.

**Closed as completed by vauvenal5** 2021-03-27 15:41 UTC
