### ISSUE TITLE
How do I view a full size version of the photo without downloading it?  

### ISSUE THREAD

**Issue by dln949** [vauvenal5/yaga#121] opened 2021-04-09 04:57 UTC
How do I view a full size version of the photo without downloading it?  

If I tap on the photo to view it full size, it then gets the green checkmark, which means I downloaded it.  But I didn't want to download it, I only wanted to view it.

**Comment by vauvenal5** [comment] 2021-04-12 09:38
Duplicate of #82

**Closed as completed by vauvenal5** 2021-04-12 09:38 UTC
