### ISSUE TITLE
App "loads" forever when Local Path is set to Nextcloud app data directory

### ISSUE THREAD

**Issue by DragonQ** [vauvenal5/yaga#86] opened 2021-02-17 09:15 UTC
I've done the following on a clean install of Yaga:

- Allowed storage permission when asked
- Logged into Nextcloud instance
- Clicked Global Settings -> Root Mapping -> Local Path
- Browsed to "/Android/media/com.nextcloud.client/nextcloud/user@domain.com%2Fnextcloud"

At this point the app shows nothing in this directory and has the loading bar at the top forever. I can click "Select" but now nothing is shown in Home View and if I go to Browse View -> User, I get the same issue (no files shown and the loading bar at the top forever).

I have a hunch that this may be because my Nextcloud instance is located in a subdirectory on the server rather than a subdomain (e.g. `domain.com/nextcloud` rather than `nextcloud.domain.com`), which means the local path has a forward-slash in it (shown as `%2F` in the Yaga app).

**Comment by vauvenal5** [comment] 2021-02-21 17:17
Hi! Yes the sub-path configuration will probably be the issue. There was a recent change in the library and while migrating I probably broke something. However, I have issues reproducing it since I have a sub-domain based configuration. Do you have the ability to temporarily create a test account on your Nextcloud instance?

**Comment by vauvenal5** [comment] 2021-02-21 19:08
Btw which version do you use?

**Comment by DragonQ** [comment] 2021-02-22 15:25
I'm using Nextcloud 20.0.7 with the latest Yaga app. I've sent you an email with details for a test user.

**Comment by vauvenal5** [comment] 2021-02-27 09:58
I was able to reproduce it and should be able to provide a fix this weekend!

**Comment by vauvenal5** [comment] 2021-02-28 11:14
This should be fixed in `v0.22.2`

Thx for the assistance!

**Comment by DragonQ** [comment] 2021-02-28 11:37
Thanks a lot, eager to test it out. :)

**Comment by vauvenal5** [comment] 2021-03-06 08:50
Is this fixed for you?

**Comment by DragonQ** [comment] 2021-03-06 09:24
I just updated to v0.22.2 via F-Droid and yes, it seems to have solved the problem. Thanks a lot!

**Closed as completed** 2021-03-06 09:31 UTC
Labels: bug, v1.0.0, internalTesting
